[package]
name = "portus"
version = "0.0.1"
authors = ["Akshay Narayan <akshayn@csail.mit.edu>"]

[dependencies]
bytes="0.4.5"
libc="0.2"
nix="0.9.0"
slog = "2"
slog-term = "2"
slog-async = "2"
time="0.1"
ccp_measure_lang = { path = "./ccp_measure_lang" }

[features]
bench = []
