[package]
name = "portus"
version = "0.5.5"
authors = ["Akshay Narayan <akshayn@csail.mit.edu>", "Frank Cangialosi <frankc@csail.mit.edu>", "Deepti Raghavan <deeptir@cs.stanford.edu>"]
description = "A Congestion Control Plane"
homepage = "https://ccp-project.github.io"
documentation = "https://docs.rs/portus"
repository = "https://github.com/ccp-project/portus"
readme = "./README.md"
license = "ISC"
edition = "2018"

[features]
default = []
lang-verbose-errors = ["nom/verbose-errors"]
ccp-quote = ["quote"]
ccp-bin = ["structopt", "proc-macro2", "colored", "regex", "libloading", "ccp-quote", "toml", "syn", "walkdir"]

[dependencies]
bytes = "0.4.5"
clap = "2.32"
crossbeam = "0.7"
itertools = "0.8"
libc = "0.2"
nix = "0.9.0"
nom = "4"
portus_export = "0.1"
slog = "2"
slog-async = "2"
slog-term = "2"
time = "0.1"
structopt = { version = "0.2", optional = true }
proc-macro2 = { version = "0.4", optional = true }
colored = { version = "1.7", optional = true }
regex = { version = "1.1", optional = true }
libloading = { version = "0.5", optional = true }
quote = { version = "0.6", optional = true }
toml = { version = "0.4", optional = true }
syn = { version = "0.15", optional = true, features = ["full", "visit", "fold", "extra-traits","parsing"] }
walkdir = { version = "2", optional = true }

[[bin]]
name = "ccp"
required-features = ["ccp-bin"]

[[bin]]
name = "cargo-compile-fast-path"
required-features = ["ccp-quote"]

[dev-dependencies]
failure = "0.1"
libccp = "0.0.12"
minion = "0.1"
