[package]
name = "ccpreno"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]

[dependencies]
slog = "2"
slog-term = "2"
slog-async = "2"
time="0.1"
portus = { path = ".." }
ccp_measure_lang = { path = "../ccp_measure_lang" }
