[package]
name = "libccp_integration_test"
version = "0.0.1"
authors = ["Deepti Raghavan <deeptir@mit.edu>", "Akshay Narayan <akshayn@csail.mit.edu>"]

[dependencies]
clap="2.29"
portus = { path = "../.." }
slog = {version = "2"}
slog-async = "2"
slog-term = "2"
time="0.1"
